# site details
name: Stinger Games
description: Independent mobile game developer.
url: http://stingergames.github.io

# social profiles. just remove unneeded profiles.
behance: #lucianmarin
dribbble: #lucianmarin
github: StingerGames
instagram: #lucianmarin
tumblr: #lucianmarin
twitter: StingerGames

highlighter: pygments
permalink: /article/:title.html

exclude: [readme.md]
include: [.htaccess]